PERCENT_LONG_SELL: "3.00%"
PERCENT_SHORT_BUY: "0.001%"
QUANTITY_SHORT_BUY_STEP: 0.1
# --------------------
STATUS_OF_GREEN_CANDLE: 1
STATUS_OF_RED_CANDLE: 1
# ---------------------
QUANTITY_LONG_BUY_STEP: 0.1
PERCENT_LONG_BUY: "-0.001%"
PERCENT_SHORT_SELL: "-3.00%"
# ---------------------
SHORT: 1
LONG: 1
BUY_PERCENT_SETTINGS: "0.1%"
SELL_PERCENT_SETTINGS: "3.00%"
LEVERAGE: 75